export const mockRegistro = {
    id: '123456',
    data: '2025-06-03T10:00:00.000Z',
    nome: 'João da Silva',
    cpf: '123.456.789-00',
    endereco: 'Rua das Flores, 123 - Centro',
    especialidade: 'Laboratorio',
    email: 'joao.silva@email.com',
    telefone: '(11) 91234-5678',
};

export const mockUser = {
    nome: 'Arthur Reis',
    usuario: 'arthur.reis',
    role: 'RECEPCAO',
};

export const mockLogs = [
    {
        id: 'log-001',
        usuarioNome: 'Carla Mendes',
        usuarioLogin: 'carla.mendes',
        acao: 'SOLICITACAO_CRIADA',
        detalhes: 'Criou solicitacao para Joao da Silva - Hemograma Completo',
        criadoEm: '2025-06-03T10:32:00.000Z',
    },
    {
        id: 'log-002',
        usuarioNome: 'Arthur Reis',
        usuarioLogin: 'arthur.reis',
        acao: 'LOGIN',
        detalhes: 'Entrou no sistema',
        criadoEm: '2025-06-03T09:15:00.000Z',
    },
    {
        id: 'log-003',
        usuarioNome: 'Fabio Torres',
        usuarioLogin: 'fabio.torres',
        acao: 'NOTA_ENVIADA',
        detalhes: 'Enviou nota fiscal para Ana Paula Costa - Ressonancia Magnetica',
        criadoEm: '2025-06-02T16:45:00.000Z',
    },
    {
        id: 'log-004',
        usuarioNome: 'Fabio Torres',
        usuarioLogin: 'fabio.torres',
        acao: 'SOLICITACAO_EMITIDA',
        detalhes: 'Emitiu nota para Carlos Eduardo Lima - Ultrassonografia Abdominal',
        criadoEm: '2025-06-02T14:20:00.000Z',
    },
    {
        id: 'log-005',
        usuarioNome: 'Carla Mendes',
        usuarioLogin: 'carla.mendes',
        acao: 'SOLICITACAO_CRIADA',
        detalhes: 'Criou solicitacao para Maria Fernanda Santos - Raio-X de Torax',
        criadoEm: '2025-06-02T11:05:00.000Z',
    },
    {
        id: 'log-006',
        usuarioNome: 'Arthur Reis',
        usuarioLogin: 'arthur.reis',
        acao: 'USUARIO_CRIADO',
        detalhes: 'Criou usuario Ricardo Souza com perfil Emissor',
        criadoEm: '2025-06-01T17:30:00.000Z',
    },
    {
        id: 'log-007',
        usuarioNome: 'Fabio Torres',
        usuarioLogin: 'fabio.torres',
        acao: 'NOTA_ENVIADA',
        detalhes: 'Enviou nota fiscal para Roberto Alves Martins - Tomografia Computadorizada',
        criadoEm: '2025-06-01T15:10:00.000Z',
    },
    {
        id: 'log-008',
        usuarioNome: 'Arthur Reis',
        usuarioLogin: 'arthur.reis',
        acao: 'USUARIO_DESATIVADO',
        detalhes: 'Desativou usuario Juliana Pires',
        criadoEm: '2025-05-31T10:00:00.000Z',
    },
    {
        id: 'log-009',
        usuarioNome: 'Carla Mendes',
        usuarioLogin: 'carla.mendes',
        acao: 'LOGIN',
        detalhes: 'Entrou no sistema',
        criadoEm: '2025-05-30T08:45:00.000Z',
    },
    {
        id: 'log-010',
        usuarioNome: 'Arthur Reis',
        usuarioLogin: 'arthur.reis',
        acao: 'USUARIO_EDITADO',
        detalhes: 'Editou usuario Carla Mendes - alterou perfil para Recepcao',
        criadoEm: '2025-05-30T08:20:00.000Z',
    },
];

export const mockUsuarios = [
    {
        id: 'usr-001',
        nome: 'Arthur Reis',
        usuario: 'arthur.reis',
        role: 'SUPER_ADMIN',
        ativo: true,
    },
    { id: 'usr-002', nome: 'Carla Mendes', usuario: 'carla.mendes', role: 'RECEPCAO', ativo: true },
    { id: 'usr-003', nome: 'Fabio Torres', usuario: 'fabio.torres', role: 'EMISSOR', ativo: true },
    {
        id: 'usr-004',
        nome: 'Juliana Pires',
        usuario: 'juliana.pires',
        role: 'RECEPCAO',
        ativo: false,
    },
    {
        id: 'usr-005',
        nome: 'Ricardo Souza',
        usuario: 'ricardo.souza',
        role: 'EMISSOR',
        ativo: true,
    },
];

export const mockSolicitacoes = [
    {
        id: 'sol-001',
        idRegistro: '123456',
        nome: 'Joao da Silva',
        cpf: '123.456.789-00',
        endereco: 'Rua das Flores, 123 - Centro',
        especialidade: 'Laboratorio',
        valor: '150,00',
        data: '2025-06-03',
        email: 'joao.silva@email.com',
        telefone: '(11) 91234-5678',
        status: 'PENDENTE',
    },
    {
        id: 'sol-002',
        idRegistro: '789012',
        nome: 'Maria Fernanda Santos',
        cpf: '987.654.321-00',
        endereco: 'Av. Paulista, 456 - Bela Vista',
        especialidade: 'Laboratorio',
        valor: '280,00',
        data: '2025-06-02',
        email: 'maria.santos@email.com',
        telefone: '',
        status: 'PENDENTE',
    },
    {
        id: 'sol-003',
        idRegistro: '345678',
        nome: 'Carlos Eduardo Lima',
        cpf: '456.789.012-00',
        endereco: 'Rua XV de Novembro, 78 - Curitiba',
        especialidade: 'Laboratorio',
        valor: '320,00',
        data: '2025-06-01',
        email: 'carlos.lima@email.com',
        telefone: '(41) 98765-4321',
        status: 'EMITIDA',
    },
    {
        id: 'sol-004',
        idRegistro: '901234',
        nome: 'Ana Paula Costa',
        cpf: '321.654.987-00',
        endereco: 'Rua das Palmeiras, 321 - Jardins',
        especialidade: 'Laboratorio',
        valor: '950,00',
        data: '2025-05-31',
        email: 'ana.costa@email.com',
        telefone: '(11) 97654-3210',
        status: 'ENVIADA_AO_PACIENTE',
    },
    {
        id: 'sol-005',
        idRegistro: '567890',
        nome: 'Roberto Alves Martins',
        cpf: '789.012.345-00',
        endereco: 'Travessa Santo Andre, 9 - Centro',
        especialidade: 'Laboratorio',
        valor: '780,00',
        data: '2025-05-30',
        email: '',
        telefone: '(21) 99887-6655',
        status: 'ENVIADA_AO_PACIENTE',
    },
];
